cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # Головна сторінка каталогу (всі товари)
    # Приклад: /
    path('', views.product_list, name='product_list'),

    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    # Сторінка каталогу для конкретної категорії
    # Приклад: /figures/
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),

    # Сторінка деталей товару (не змінюється)
    # Приклад: /1/funko-pop-iron-man/
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    # Інші шляхи, як-от wishlist, залишаються без змін

]

shop/models.py
from django.urls import reverse
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand',
                        args=[self.slug])

class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Країна'
        verbose_name_plural = 'Країни'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_country',
                        args=[self.slug])

class Universe(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Всесвіт'
        verbose_name_plural = 'Всесвіти'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_universe',
                        args=[self.slug])

class Character(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Персонаж'
        verbose_name_plural = 'Персонажі'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_character',
                        args=[self.slug])

class Size(models.Model):
    value = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('value',)
        verbose_name = 'Розмір'
        verbose_name_plural = 'Розміри'

    def __str__(self):
        return self.value

    def get_absolute_url(self):
        return reverse('shop:product_list_by_size',
                        args=[self.slug])

class Material(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Матеріал'
        verbose_name_plural = 'Матеріали'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_material',
                        args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    discount = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    universe = models.ManyToManyField(Universe, blank=True)
    character = models.ManyToManyField(Character, blank=True)
    size = models.ManyToManyField(Size, blank=True)
    material = models.ManyToManyField(Material, blank=True)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug']),]
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

    @property
    def sell_price(self):
        if self.discount > 0:
            return int(self.price * (1 - self.discount / 100))
        return int(self.price)


class ProductImage(models.Model):

    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d')

    def __str__(self):
        return f"Image for {self.product.name}"

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, Brand, Country, Universe, Character, Size, Material
from cart.forms import CartAddProductForm
from cart.cart import Cart
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def product_list(request, category_slug=None):
    """
    Відображає список товарів з можливістю фільтрації за категорією
    та множинними GET-параметрами.
    """
    category = None
    products = Product.objects.filter(available=True)

    search_query = request.GET.get('q', '').strip()
    if search_query:
        products = products.filter(
            Q(name__iregex=search_query) |
            Q(description__iregex=search_query)
        )

    # 1. Фільтрація по категорії (якщо є в URL)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    # 2. Отримання параметрів фільтрації з URL
    # request.GET.get('brand') візьме значення ?brand=...
    filter_params = {
        'brand': request.GET.get('brand'),
        'country': request.GET.get('country'),
        'universe': request.GET.get('universe'),
        'character': request.GET.get('character'),
        'size': request.GET.get('size'),
        'material': request.GET.get('material'),
    }

    # 3. Застосування фільтрів до запиту
    if filter_params['brand']:
        slugs = filter_params['brand'].split(',')
        products = products.filter(brand__slug__in=slugs)

    if filter_params['country']:
        slugs = filter_params['country'].split(',')
        products = products.filter(country__slug__in=slugs)

    if filter_params['universe']:
        slugs = filter_params['universe'].split(',')
        products = products.filter(universe__slug__in=slugs)
    
    if filter_params['character']:
        slugs = filter_params['character'].split(',')
        products = products.filter(character__slug__in=slugs)

    if filter_params['size']:
        slugs = filter_params['size'].split(',')
        products = products.filter(size__slug__in=slugs)

    if filter_params['material']:
        slugs = filter_params['material'].split(',')
        products = products.filter(material__slug__in=slugs)

    # 4. Видалення дублікатів, що важливо для ManyToMany полів
    products = products.distinct()

    # 5. Підготовка контексту для передачі в шаблон
    context = {
        'category': category,
        'products': products,
        'search_query': search_query,
        
        # Списки для відображення всіх опцій у фільтрах
        'categories': Category.objects.all(),
        'brands': Brand.objects.all(),
        'countries': Country.objects.all(),
        'universes': Universe.objects.all(),
        'characters': Character.objects.all(),
        'sizes': Size.objects.all(),
        'materials': Material.objects.all(),
        
        # Списки обраних slug'ів для встановлення 'checked' у чекбоксах
        'selected_brands': filter_params['brand'].split(',') if filter_params['brand'] else [],
        'selected_countries': filter_params['country'].split(',') if filter_params['country'] else [],
        'selected_universes': filter_params['universe'].split(',') if filter_params['universe'] else [],
        'selected_characters': filter_params['character'].split(',') if filter_params['character'] else [],
        'selected_sizes': filter_params['size'].split(',') if filter_params['size'] else [],
        'selected_materials': filter_params['material'].split(',') if filter_params['material'] else [],
    }
    
    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart = Cart(request)
    in_cart = str(product.id) in cart.cart
    cart_product_form = CartAddProductForm(product=product)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'in_cart': in_cart,
                   })



@login_required
@require_POST
def toggle_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    profile = request.user.profile

    if product in profile.wishlist.all():
        profile.wishlist.remove(product)
        action = 'removed'
    else:
        profile.wishlist.add(product)
        action = 'added'

    return JsonResponse({
        'status': 'ok',
        'action': action,
        'wishlist_count': profile.wishlist.count()
    })

@login_required
def wishlist_view(request):
    wishlist_products = request.user.profile.wishlist.all()
    return render(request, 'shop/wishlist.html', {'wishlist_products': wishlist_products})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="product-detail-container">
    
    <div class="product-gallery">
        <div class="main-image-container">
            <img src="{% if product.images.all %}{{ product.images.first.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}" id="mainImage" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="thumbnail-container">
            {% for img in product.images.all %}
                <img src="{{ img.image.url }}" class="thumbnail" alt="Мініатюра {{ forloop.counter }}" onclick="changeImage('{{ img.image.url }}', this)">
            {% endfor %}
        </div>
    </div>

    <div class="product-info">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        
        {% if product.discount > 0 %}
            <div class="card-discount">
                <p>
                    <span class="old-price">{{ product.price }} ₴</span>
                    <span class="discount-percent">-{{ product.discount }}%</span>
                </p>
                <p class="new-price">{{ product.sell_price }} ₴</p>
            </div>
        {% else %}
            <p class="price">{{ product.price}} ₴</p>
        {% endif %}
        
        <div class="product-description">
            {{ product.description|linebreaks }}
        </div>
        
        {% if in_cart %}
            <div class="alert alert-info mt-3" role="alert">
                Цей товар вже у вашому кошику
            </div>
        {% else %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Додати у кошик" class="btn btn-success">
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Товар{% endif %}
{% endblock %}
{% block content %}
<div class="top-container">
<button id="open-filter-btn" class="filter-trigger-button">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>
    <span>Фільтри</span>
</button>
<div class="filter-overlay"></div>

<div id="filter-sidebar">
    <div class="sidebar-header">
        <h3>Фільтри</h3>
        <span class="sidebarr-close">&times;</span>
    </div>
    
    <div class="sidebar-content">
        <div class="product-filters">

            <!-- Фільтр: Бренд -->
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Бренд</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for b in brands %}
                        <li>
                            <label>
                                <input type="checkbox" name="brand" value="{{ b.slug }}" {% if b.slug in selected_brands %}checked{% endif %}>
                                {{ b.name }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Фільтр: Країна -->
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Країна</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for co in countries %}
                        <li>
                            <label>
                                <input type="checkbox" name="country" value="{{ co.slug }}" {% if co.slug in selected_countries %}checked{% endif %}>
                                {{ co.name }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Фільтр: Всесвіт -->
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Всесвіт</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for u in universes %}
                        <li>
                            <label>
                                <input type="checkbox" name="universe" value="{{ u.slug }}" {% if u.slug in selected_universes %}checked{% endif %}>
                                {{ u.name }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Персонаж</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for ch in characters %}
                        <li>
                            <label>
                                <input type="checkbox" name="character" value="{{ ch.slug }}" {% if ch.slug in selected_characters %}checked{% endif %}>
                                {{ ch.name }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Фільтр: Розмір -->
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Розмір</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for s in sizes %}
                        <li>
                            <label>
                                <input type="checkbox" name="size" value="{{ s.slug }}" {% if s.slug in selected_sizes %}checked{% endif %}>
                                {{ s.value }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Фільтр: Матеріал -->
            <div class="filter-group">
                <button class="accordion-toggle">
                    <span>Матеріал</span>
                    <span class="toggle-icon"></span>
                </button>
                <div class="filter-options">
                    <ul>
                        {% for m in materials %}
                        <li>
                            <label>
                                <input type="checkbox" name="material" value="{{ m.slug }}" {% if m.slug in selected_materials %}checked{% endif %}>
                                {{ m.name }}
                            </label>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>

    <div class="sidebar-footer">
        <button id="apply-filters-btn" class="apply-btn">Застосувати</button>
        <button id="reset-filters-btn" class="reset-btn">Скинути</button>
    </div>
</div>


        <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Товари{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.images.all %}{{ product.images.first.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}"
                    alt="{{ product.name }}"
                    class="product-image">
                    </a>
                <div class="name-info">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                </div>
                {% if user.is_authenticated %}
                    <form action="{% url 'shop:toggle_wishlist' product.id %}" method="POST" class="wishlist-form">
                        {% csrf_token %}
                        <button type="submit"
                                class="wishlist-toggle-btn {% if product in user.profile.wishlist.all %}active{% endif %}"
                                data-liked-src="{% static 'img/liked_black.png' %}"
                                data-unliked-src="{% static 'img/like_black.png' %}">

                            {% if product in user.profile.wishlist.all %}
                                <img src="{% static 'img/liked_black.png' %}" alt="В избранном">
                            {% else %}
                                <img src="{% static 'img/like_black.png' %}" alt="Добавить в избранное">
                            {% endif %}
                        </button>
                    </form>
                {% else %}
                <div class="wish-login">
                    <a href="{% url 'account_login' %}?next={{ request.path }}">
                        <img src="{% static 'img/like_black.png' %}" alt="Войдите, чтобы добавить в избранное">
                    </a>
                </div>
                {% endif %}
                {% if product.discount > 0 %}
                    <div class="discount-info">
                        -{{ product.discount }}%
                    </div>
                    <div class="price">
                        <span class="old-price">{{ product.price }} ₴</span>
                        <span class="new-price">{{ product.sell_price }} ₴</span>
                {% else %}
                    <span class="price">{{ product.price }} ₴</span>
                {% endif %}
                    </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}