cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # Головна сторінка каталогу (всі товари)
    # Приклад: /
    path('', views.product_list, name='product_list'),

    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    # Сторінка каталогу для конкретної категорії
    # Приклад: /figures/
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),

    # Сторінка деталей товару (не змінюється)
    # Приклад: /1/funko-pop-iron-man/
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    # Інші шляхи, як-от wishlist, залишаються без змін

]

shop/models.py
from django.urls import reverse
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand',
                        args=[self.slug])

class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Країна'
        verbose_name_plural = 'Країни'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_country',
                        args=[self.slug])

class Universe(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Всесвіт'
        verbose_name_plural = 'Всесвіти'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_universe',
                        args=[self.slug])

class Character(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Персонаж'
        verbose_name_plural = 'Персонажі'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_character',
                        args=[self.slug])

class Size(models.Model):
    value = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('value',)
        verbose_name = 'Розмір'
        verbose_name_plural = 'Розміри'

    def __str__(self):
        return self.value

    def get_absolute_url(self):
        return reverse('shop:product_list_by_size',
                        args=[self.slug])

class Material(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Матеріал'
        verbose_name_plural = 'Матеріали'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_material',
                        args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    discount = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    universe = models.ManyToManyField(Universe, blank=True)
    character = models.ManyToManyField(Character, blank=True)
    size = models.ManyToManyField(Size, blank=True)
    material = models.ManyToManyField(Material, blank=True)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug']),]
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

    @property
    def sell_price(self):
        if self.discount > 0:
            return int(self.price * (1 - self.discount / 100))
        return int(self.price)


class ProductImage(models.Model):

    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d')

    def __str__(self):
        return f"Image for {self.product.name}"

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, Brand, Country, Universe, Character, Size, Material
from cart.forms import CartAddProductForm
from cart.cart import Cart
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def product_list(request, category_slug=None):
    """
    Відображає список товарів з можливістю фільтрації за категорією
    та множинними GET-параметрами.
    """
    category = None
    products = Product.objects.filter(available=True)

    search_query = request.GET.get('q', '').strip()
    if search_query:
        products = products.filter(
            Q(name__iregex=search_query) |
            Q(description__iregex=search_query)
        )

    # 1. Фільтрація по категорії (якщо є в URL)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    # 2. Отримання параметрів фільтрації з URL
    # request.GET.get('brand') візьме значення ?brand=...
    filter_params = {
        'brand': request.GET.get('brand'),
        'country': request.GET.get('country'),
        'universe': request.GET.get('universe'),
        'character': request.GET.get('character'),
        'size': request.GET.get('size'),
        'material': request.GET.get('material'),
    }

    # 3. Застосування фільтрів до запиту
    if filter_params['brand']:
        slugs = filter_params['brand'].split(',')
        products = products.filter(brand__slug__in=slugs)

    if filter_params['country']:
        slugs = filter_params['country'].split(',')
        products = products.filter(country__slug__in=slugs)

    if filter_params['universe']:
        slugs = filter_params['universe'].split(',')
        products = products.filter(universe__slug__in=slugs)
    
    if filter_params['character']:
        slugs = filter_params['character'].split(',')
        products = products.filter(character__slug__in=slugs)

    if filter_params['size']:
        slugs = filter_params['size'].split(',')
        products = products.filter(size__slug__in=slugs)

    if filter_params['material']:
        slugs = filter_params['material'].split(',')
        products = products.filter(material__slug__in=slugs)

    # 4. Видалення дублікатів, що важливо для ManyToMany полів
    products = products.distinct()

    # 5. Підготовка контексту для передачі в шаблон
    context = {
        'category': category,
        'products': products,
        'search_query': search_query,
        
        # Списки для відображення всіх опцій у фільтрах
        'categories': Category.objects.all(),
        'brands': Brand.objects.all(),
        'countries': Country.objects.all(),
        'universes': Universe.objects.all(),
        'characters': Character.objects.all(),
        'sizes': Size.objects.all(),
        'materials': Material.objects.all(),
        
        # Списки обраних slug'ів для встановлення 'checked' у чекбоксах
        'selected_brands': filter_params['brand'].split(',') if filter_params['brand'] else [],
        'selected_countries': filter_params['country'].split(',') if filter_params['country'] else [],
        'selected_universes': filter_params['universe'].split(',') if filter_params['universe'] else [],
        'selected_characters': filter_params['character'].split(',') if filter_params['character'] else [],
        'selected_sizes': filter_params['size'].split(',') if filter_params['size'] else [],
        'selected_materials': filter_params['material'].split(',') if filter_params['material'] else [],
    }
    
    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart = Cart(request)
    in_cart = str(product.id) in cart.cart
    cart_product_form = CartAddProductForm(product=product)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'in_cart': in_cart,
                   })



@login_required
@require_POST
def toggle_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    profile = request.user.profile

    if product in profile.wishlist.all():
        profile.wishlist.remove(product)
        action = 'removed'
    else:
        profile.wishlist.add(product)
        action = 'added'

    return JsonResponse({
        'status': 'ok',
        'action': action,
        'wishlist_count': profile.wishlist.count()
    })

@login_required
def wishlist_view(request):
    wishlist_products = request.user.profile.wishlist.all()
    return render(request, 'shop/wishlist.html', {'wishlist_products': wishlist_products})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Figure{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link href="{% static 'css/profile_edit.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<body>
<div class="container">
    <div id="header">
        <div class="nav-bg">
            <nav>
                <div class="nav-left">
                    <div class="humburger-menu">
                        <img src="{% static 'img/humburger.svg' %}" alt="Menu">
                    </div>
                    <div id="search-trigger" class="search">
                        <img src="{% static 'img/search_white.svg' %}" alt="Search">
                    </div>
                    <div class="search-overlay" id="search-overlay">
                        <div class="search-container">
                            <form action="{% url 'shop:product_list' %}" method="get" class="search-form">
                                <input type="text" name="q" placeholder="Пошук товарів..." value="{{ search_query }}">
                                <button type="submit">
                                    <img src="{% static 'img/search_black.png' %}" alt="Search" class="search-icon">
                                </button>
                                <span class="close-search"></span>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="logo-container">
                    <a href="/" class="logo">Figure</a>
                </div>
                <div class="nav-right">
                    <div class="cart">
                        <a href="{% url 'shop:wishlist' %}">
                            <img src="{% static 'img/like.png' %}" alt="Like">
                        </a>
                    </div>
                    <div class = "cart-count liked-count">
                <span id="wishlist-count">
                    {% if wishlist_count > 0 %}
                        <span class="badge">{{ wishlist_count }}</span>
                    {% else %}
                        0
                    {% endif %}
                </span>
                </div>
                <div class="cart">
                    <a href="{% url 'cart:cart_detail' %}">
                        <img src="{% static 'img/cart.png' %}" alt="Cart">
                    </a>
                    </div>
                    <div class = cart-count>
                        {% if request.session.cart %}
                            <span class="badge">{{ request.session.cart|length }}</span>
                        {% else %}
                            0
                        {% endif %}
                </div>
                </div>
            </nav>
        </div>
    </div>

<div class="sidebar-overlay"></div>

<div id="sidebar">
    <div class="sidebar-content">
        <span class="sidebar-close">&times;</span>
        
        <div class="sidebar-header">
            <a href="/users/">Профіль</a>
        </div>

        <div class="filter-section">
            <button class="accordion">
                <span>Категорії</span>
                <span class="toggle-icon"></span>
            </button>
            <div class="filter-list">
                <ul>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
    {% block content %}
    {% endblock %}

</div>
</body>
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/wishlist.js' %}"></script>
<script src="{% static 'js/list.js' %}"></script>
<script src="{% static 'js/detail.js' %}"></script>
</html>

shop/templates/shop/wishlist.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Мої обрані товари
{% endblock %}

{% block content %}
<div class="wishlist-container">
    <h1>Мої обрані товари</h1>
    
    {% if wishlist_products %}
        <div class="row">
            {% for product in wishlist_products %}
                <div class="col-sm-6 col-md-4 col-lg-3 mb-4 d-flex align-items-stretch">
                    <div class="card w-100">
                        <a href="{{ product.get_absolute_url }}">
                           <img src="{% if product.images.all %}{{ product.images.first.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}" class="card-img-top" alt="{{ product.name }}">
                        </a>
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">
                                <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">{{ product.name }}</a>
                            </h5>
                            <div class="mt-auto">
                                <p class="card-text mb-2"><strong>{{ product.price }} ₴</strong></p>
                                <a href="{{ product.get_absolute_url }}" class="btn btn-primary w-100">До товару</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="text-center wishlist-empty-state">
            <p class="lead">Ваш список обраного порожній.</p>
            <p>Ви можете додавати товари, натискаючи на сердечко ❤️️ на сторінці товару.</p>
            <a href="{% url 'shop:product_list' %}" class="btn btn-success mt-3">Почати покупки</a>
        </div>
    {% endif %}
</div>
{% endblock %}